# Requires Python 3.10+
"""s3bak - Unified S3 backup/restore tool

Backs up and restores configured directories or files to/from S3.

Config: ~/.config/s3bak/config.py (override: $S3BAK_CONFIG)
"""

from __future__ import annotations

import calendar
import concurrent.futures
import datetime
import os
import re
import shlex
import shutil
import signal
import stat as stat_mod
import subprocess
import sys
import tempfile
import threading

try:
    import grp
except ModuleNotFoundError:
    grp = None  # type: ignore[assignment]
try:
    import pwd
except ModuleNotFoundError:
    pwd = None  # type: ignore[assignment]
from collections.abc import Callable, Iterator
from dataclasses import dataclass, field
from typing import Any, NoReturn

PROG = "s3bak"
IS_WINDOWS = sys.platform == "win32"

# =============================================================================
# Utilities
# =============================================================================

_output_lock = threading.Lock()


def err(msg: str) -> None:
    sys.stderr.write(f"{PROG}: {msg}\n")
    sys.stderr.flush()


def die(msg: str) -> NoReturn:
    err(msg)
    sys.exit(1)


def write_output(text: str) -> None:
    with _output_lock:
        sys.stdout.write(text)
        sys.stdout.flush()


def write_stderr(text: str) -> None:
    with _output_lock:
        sys.stderr.write(text)
        sys.stderr.flush()


def echo_command(verbose: bool, args: list[str]) -> None:
    if verbose:
        write_stderr(f"+ {shlex.join(args)}\n")


def expand_home(path: str) -> str:
    # os.path.expanduser on Windows-native Python (ucrt64/mingw) resolves "~"
    # via USERPROFILE, which ignores the msys HOME. Prefer HOME when set.
    if not path.startswith("~"):
        return path
    home = os.environ.get("HOME")
    if home and (path == "~" or path.startswith("~/")):
        return home + path[1:]
    return os.path.expanduser(path)


# =============================================================================
# Shell quoting (stat QUOTING_STYLE=shell-always compatible)
# =============================================================================


def shell_always_quote(s: str) -> str:
    return "'" + s.replace("'", "'\\''") + "'"


def shell_unquote(s: str) -> str:
    if s.startswith("'"):
        s = s[1:-1]
        s = s.replace("'\\'", "\x00").replace("'", "")
        s = s.replace("\x00", "'")
        return s
    if s.startswith('"'):
        return s[1:-1]
    return s


def parse_fname(fname_field: str) -> tuple[str, str | None]:
    m = re.match(r"^(.+?)' -> '(.+)$", fname_field)
    if m:
        link_part = m.group(1) + "'"
        target_part = "'" + m.group(2)
        return shell_unquote(link_part), shell_unquote(target_part)
    return shell_unquote(fname_field), None


def parse_timestamp(date_str: str, time_str: str, zone_str: str) -> float:
    # Expected formats (generated by format_stat_line):
    #   date_str: "YYYY-MM-DD"
    #   time_str: "HH:MM:SS" or "HH:MM:SS.nnnnnnnnn"
    #   zone_str: "+HHMM" or "-HHMM"
    # Fast path avoids datetime.strptime, which dominates manifest parsing.
    try:
        year = int(date_str[0:4])
        month = int(date_str[5:7])
        day = int(date_str[8:10])
        hour = int(time_str[0:2])
        minute = int(time_str[3:5])
        second = int(time_str[6:8])
        if zone_str[0] == "+":
            sign = 1
        elif zone_str[0] == "-":
            sign = -1
        else:
            raise ValueError(f"bad zone: {zone_str}")
        tz_h = int(zone_str[1:3])
        tz_m = int(zone_str[3:5])
    except (ValueError, IndexError):
        # Fall back to strptime for any unexpected shape.
        time_fb = time_str.split(".")[0]
        dt = datetime.datetime.strptime(f"{date_str} {time_fb} {zone_str}", "%Y-%m-%d %H:%M:%S %z")
        return dt.timestamp()
    utc_epoch = calendar.timegm((year, month, day, hour, minute, second, 0, 0, 0))
    return float(utc_epoch - sign * (tz_h * 3600 + tz_m * 60))


# =============================================================================
# Manifest entry parsing
# =============================================================================


@dataclass(frozen=True)
class ManifestEntry:
    rel: str  # original name field: ".", "./foo/bar", or bare basename
    mode_str: str
    user: str
    group: str
    size_str: str
    date_str: str
    time_str: str
    zone_str: str
    sym_target: str | None

    @property
    def mode_int(self) -> int:
        return int(self.mode_str, 8)

    @property
    def size_int(self) -> int:
        return int(self.size_str)

    @property
    def epoch(self) -> int:
        return int(parse_timestamp(self.date_str, self.time_str, self.zone_str))


def parse_manifest_line(line: str) -> ManifestEntry | None:
    line = line.rstrip("\n")
    if not line:
        return None
    parts = line.split(None, 7)
    if len(parts) < 8:
        return None
    fname, sym = parse_fname(parts[7])
    return ManifestEntry(
        rel=fname,
        mode_str=parts[0],
        user=parts[1],
        group=parts[2],
        size_str=parts[3],
        date_str=parts[4],
        time_str=parts[5],
        zone_str=parts[6],
        sym_target=sym,
    )


def iter_manifest(manifest_path: str) -> Iterator[ManifestEntry]:
    with open(manifest_path) as f:
        for line in f:
            entry = parse_manifest_line(line)
            if entry is not None:
                yield entry


def resolve_manifest_rel(rel_field: str, sub: str | None) -> str | None:
    """Translate manifest rel ('.' / './x/y' / 'basename') into the
    sub-relative form ('.' for self, 'x/y' for descendants, None to skip).
    """
    rel = rel_field.removeprefix("./")
    if rel_field == ".":
        rel = "."
    if sub is None:
        return rel
    if rel == sub:
        return "."
    if rel.startswith(sub + "/"):
        return rel[len(sub) + 1 :]
    return None


def manifest_target(
    entry: ManifestEntry, outpath: str, is_dir: bool, sub: str | None
) -> tuple[str, str] | None:
    """Resolve the manifest entry to (target_path, sub_rel) or None to skip."""
    rel = resolve_manifest_rel(entry.rel, sub)
    if rel is None:
        return None
    if is_dir:
        target = outpath if rel == "." else os.path.join(outpath, rel)
    else:
        target = outpath
    return target, rel


# =============================================================================
# Manifest-vs-local diff
# =============================================================================


@dataclass
class EntryDiff:
    status: str | None  # None=match, "M"=modified, "D"=missing/wrong-type
    tags: list[str]  # ["mode", "mtime", "size", "link"]
    details: list[str]  # human-readable per-field detail lines

    @property
    def is_match(self) -> bool:
        return self.status is None


def compare_to_local(
    entry: ManifestEntry,
    target: str,
    *,
    use_color: bool = False,
    ignore_dir_mtime: bool = False,
) -> EntryDiff:
    diff = EntryDiff(status=None, tags=[], details=[])

    try:
        st: os.stat_result | None = os.lstat(target)
    except OSError:
        st = None

    if entry.sym_target is not None:
        if st is None or not stat_mod.S_ISLNK(st.st_mode):
            diff.status = "D"
            return diff
        try:
            loc_link = os.readlink(target)
        except OSError:
            loc_link = ""
        if loc_link != entry.sym_target:
            diff.status = "M"
            diff.tags.append("link")
            diff.details.append(f"link: remote={entry.sym_target} local={loc_link}")
        return diff

    if st is None:
        diff.status = "D"
        return diff

    if stat_mod.S_ISLNK(st.st_mode):
        try:
            is_dir_local = stat_mod.S_ISDIR(os.stat(target).st_mode)
        except OSError:
            is_dir_local = False
    else:
        is_dir_local = stat_mod.S_ISDIR(st.st_mode)

    if not is_dir_local:
        loc_size = st.st_size
        if str(loc_size) != entry.size_str:
            diff.status = "M"
            diff.tags.append("size")
            try:
                remote_size_int = int(entry.size_str)
            except ValueError:
                remote_size_int = None
            if remote_size_int is not None:
                if remote_size_int < loc_size:
                    cmp = "<"
                    remote_disp = entry.size_str
                    local_disp = _color_wrap(str(loc_size), use_color)
                else:
                    cmp = ">"
                    remote_disp = _color_wrap(entry.size_str, use_color)
                    local_disp = str(loc_size)
                diff_str = _humanize_size_diff(loc_size - remote_size_int)
                diff.details.append(
                    f"size: remote={remote_disp} {cmp} local={local_disp} ({diff_str})"
                )
            else:
                diff.details.append(f"size: remote={entry.size_str} local={loc_size}")

    loc_mode = format(stat_mod.S_IMODE(st.st_mode), "o")
    mode_differs = loc_mode != entry.mode_str
    if mode_differs and IS_WINDOWS:
        # Windows-native Python (incl. msys2 UCRT64) reports synthetic modes
        # via os.stat: 0o666 for writable files, 0o444 for read-only - not
        # the Unix permission bits. Only the owner-write bit is meaningful.
        try:
            if (entry.mode_int & 0o200) == (st.st_mode & 0o200):
                mode_differs = False
        except ValueError:
            pass
    if mode_differs:
        diff.status = "M"
        diff.tags.append("mode")
        diff.details.append(f"mode: remote={entry.mode_str} local={loc_mode}")

    # A directory's mtime changes whenever its children are added/removed, so
    # it is noise in `status` and is suppressed there (ignore_dir_mtime=True).
    # The restore path (_manifest_matches_local) keeps the default and still
    # detects dir mtime drift so apply_manifest can restore it.
    if ignore_dir_mtime and is_dir_local:
        return diff

    try:
        loc_mtime = int(st.st_mtime)
        remote_epoch = entry.epoch
    except ValueError:
        return diff
    if loc_mtime != remote_epoch:
        fmt_local = datetime.datetime.fromtimestamp(loc_mtime).strftime("%Y-%m-%d %H:%M:%S")
        fmt_remote = datetime.datetime.fromtimestamp(remote_epoch).strftime("%Y-%m-%d %H:%M:%S")
        diff.status = "M"
        diff.tags.append("mtime")
        if remote_epoch < loc_mtime:
            cmp = "<"
            remote_disp = fmt_remote
            local_disp = _color_wrap(fmt_local, use_color)
        else:
            cmp = ">"
            remote_disp = _color_wrap(fmt_remote, use_color)
            local_disp = fmt_local
        diff_str = _humanize_duration(loc_mtime - remote_epoch)
        diff.details.append(f"mtime: remote={remote_disp} {cmp} local={local_disp} ({diff_str})")

    return diff


# =============================================================================
# Config / Options
# =============================================================================


@dataclass
class Config:
    profile: str
    prefix: str
    bucket: str
    path_prefix: str
    entries: dict[str, dict[str, Any]]
    store: Boto3S3Store | None = None


@dataclass
class Opts:
    dryrun: bool = False
    delete: bool = False
    meta_only: bool = False
    data_only: bool = False
    verbose: bool = False
    outpath: str | None = None
    color: str = "auto"


def load_config() -> Config:
    config_path = os.environ.get("S3BAK_CONFIG")
    if not config_path:
        config_path = expand_home("~/.config/s3bak/config.py")

    if not os.path.isfile(config_path):
        config_sh = expand_home("~/.config/s3bak/config.sh")
        if os.path.isfile(config_sh):
            die(
                f"found {config_sh} but s3bak now requires config.py\n"
                f"  Please create: {config_path}"
            )
        die(
            f"config file not found: {config_path}\n\n"
            f"Create it with contents like:\n\n"
            f'  profile = "default"\n'
            f'  prefix  = "s3://my-bucket/backup"\n\n'
            f"  entries = {{\n"
            f'      "home-docs": {{"path": "/home/user/Documents"}},\n'
            f"  }}"
        )

    ns: dict[str, Any] = {}
    with open(config_path) as f:
        code = f.read()
    try:
        exec(compile(code, config_path, "exec"), ns)
    except Exception as e:
        die(f"error loading {config_path}: {e}")

    profile: str | None = ns.get("profile")
    prefix: str | None = ns.get("prefix")
    entries: dict[str, dict[str, Any]] | None = ns.get("entries")

    if not profile or not prefix:
        die(f"profile and prefix must be set in {config_path}")
    if not entries:
        die(f"no entries defined in {config_path}")
    if "all" in entries:
        err("warning: entry name 'all' conflicts with --all flag; consider renaming")
    if not prefix.startswith("s3://"):
        die(f"prefix must start with s3:// (got '{prefix}')")

    rest = prefix[5:]
    bucket = rest.split("/", 1)[0]
    path_prefix = rest.split("/", 1)[1].strip("/") if "/" in rest else ""

    if not bucket:
        die(f"could not parse bucket from prefix='{prefix}'")

    cfg = Config(
        profile=profile,
        prefix=prefix,
        bucket=bucket,
        path_prefix=path_prefix,
        entries=entries,
    )
    cfg.store = Boto3S3Store(profile, prefix, bucket, path_prefix)
    return cfg


# =============================================================================
# Remote object store
# =============================================================================


@dataclass
class ObjectMeta:
    """Subset of S3 head-object response that callers use."""

    key: str
    size: int = 0
    metadata: dict[str, str] = field(default_factory=dict)


@dataclass
class TransferResult:
    """Result of a sync/copy operation that may print CLI output."""

    returncode: int
    stdout: str = ""
    stderr: str = ""


class Boto3S3Store:
    """Object storage backend for s3bak, built on the boto3-s3 library.

    Transfers (cp / sync) and listing go through the boto3-s3 ``S3`` API
    in-process; head-object / list-objects-v2 use the underlying boto3 client.
    Endpoint and credentials come from the AWS environment/profile, so the
    MinIO dev profile and real AWS both work without special-casing.

    `rel_key` is a path relative to the configured prefix (e.g. "bin",
    "bin/foo.txt", "bin-ls-l.txt"). The store internally prepends
    `path_prefix` for boto3 calls and `prefix` (the s3:// URL) for cp / sync.
    """

    def __init__(self, profile: str, prefix: str, bucket: str, path_prefix: str):
        self.profile = profile
        self.prefix = prefix  # full s3:// URL
        self.bucket = bucket
        self.path_prefix = path_prefix
        self._s3_cache: Any = None
        self._client_cache: Any = None

    # --- internal ----------------------------------------------------------
    def _s3(self) -> Any:
        """Lazily build the boto3-s3 S3 orchestrator for the configured profile."""
        if self._s3_cache is None:
            import boto3
            from boto3_s3 import S3

            self._s3_cache = S3(session=boto3.Session(profile_name=self.profile))
        return self._s3_cache

    def _client(self) -> Any:
        if self._client_cache is None:
            self._client_cache = self._s3().client()
        return self._client_cache

    def _api_key(self, rel_key: str) -> str:
        return f"{self.path_prefix}/{rel_key}" if self.path_prefix else rel_key

    def _s3_url(self, rel_key: str = "") -> str:
        return f"{self.prefix}/{rel_key}" if rel_key else self.prefix

    def _transfer(self, verbose: bool, label: str, op: Callable[[Any], None]) -> TransferResult:
        """Run a boto3-s3 transfer op, collecting aws-style result lines.

        `op(on_result)` calls the S3 method with the given result callback;
        SUCCEEDED/DRYRUN items become 'upload:'/'download:'/'delete:' stdout
        lines, failures become stderr lines, and any boto3-s3 error sets
        returncode 1. on_result runs on s3transfer worker threads, so a lock
        guards the result lists.
        """
        from boto3_s3 import Boto3S3Error, OpKind, OpOutcome

        if verbose:
            write_stderr(f"+ (boto3-s3) {label}\n")
        lines: list[str] = []
        errs: list[str] = []
        lock = threading.Lock()

        def on_result(r: Any) -> None:
            if r.outcome in (OpOutcome.SUCCEEDED, OpOutcome.DRYRUN):
                pre = "(dryrun) " if r.outcome is OpOutcome.DRYRUN else ""
                if r.kind is OpKind.DELETE:
                    line = f"{pre}delete: {r.key}"
                elif r.src is not None and r.dest is not None:
                    line = f"{pre}{r.kind.value}: {r.src} to {r.dest}"
                else:
                    return
                with lock:
                    lines.append(line)
            elif r.outcome is OpOutcome.FAILED:
                with lock:
                    errs.append(f"{r.key}: {r.error}")

        try:
            op(on_result)
            rc = 0
        except Boto3S3Error as e:
            rc = 1
            errs.append(str(e))
        return TransferResult(returncode=rc, stdout="\n".join(lines), stderr="\n".join(errs))

    # --- Public API --------------------------------------------------------
    def head_object(self, rel_key: str, *, verbose: bool = False) -> ObjectMeta | None:
        from botocore.exceptions import ClientError

        key = self._api_key(rel_key)
        if verbose:
            write_stderr(f"+ (boto3) head_object s3://{self.bucket}/{key}\n")
        try:
            data = self._client().head_object(Bucket=self.bucket, Key=key)
        except ClientError as e:
            if e.response.get("Error", {}).get("Code", "") in ("404", "NoSuchKey", "NotFound"):
                return None
            raise
        return ObjectMeta(
            key=rel_key,
            size=int(data.get("ContentLength", 0)),
            metadata=dict(data.get("Metadata") or {}),
        )

    def list_keys_under(self, rel_prefix: str, *, verbose: bool = False) -> set[str]:
        norm = rel_prefix if rel_prefix.endswith("/") else f"{rel_prefix}/"
        prefix = self._api_key(norm)
        if verbose:
            write_stderr(f"+ (boto3) list_objects_v2 s3://{self.bucket}/{prefix}\n")
        keys: set[str] = set()
        paginator = self._client().get_paginator("list_objects_v2")
        for page in paginator.paginate(Bucket=self.bucket, Prefix=prefix):
            for obj in page.get("Contents", []):
                rel = obj["Key"][len(prefix) :]
                if rel:
                    keys.add(rel)
        return keys

    def list_top_level_lines(self, *, verbose: bool = False) -> list[str]:
        from boto3_s3 import FileKind

        if verbose:
            write_stderr(f"+ (boto3-s3) ls {self.prefix}/\n")
        names: list[str] = []
        for info in self._s3().ls(f"{self.prefix}/", recursive=False):
            if info.kind is FileKind.FILE:
                names.append(info.key.rsplit("/", 1)[-1])
        return names

    def get_object(
        self,
        rel_key: str,
        dest_path: str,
        *,
        verbose: bool = False,
        check: bool = True,
    ) -> bool:
        from boto3_s3 import Boto3S3Error

        if verbose:
            write_stderr(f"+ (boto3-s3) cp {self._s3_url(rel_key)} {dest_path}\n")
        try:
            self._s3().cp(self._s3_url(rel_key), dest_path)
            return True
        except Boto3S3Error:
            return False

    def stream_object_to_stdout(self, rel_key: str, *, verbose: bool = False) -> int:
        from boto3_s3 import Boto3S3Error, StdioStorage

        if verbose:
            write_stderr(f"+ (boto3-s3) cp {self._s3_url(rel_key)} -\n")
        try:
            self._s3().cp(self._s3_url(rel_key), StdioStorage())
            return 0
        except Boto3S3Error as e:
            write_stderr(f"{e}\n")
            return 1

    def sync_down(
        self,
        rel_prefix: str,
        dest_dir: str,
        *,
        verbose: bool = False,
    ) -> TransferResult:
        src = f"{self._s3_url(rel_prefix)}/" if rel_prefix else f"{self.prefix}/"
        return self._transfer(
            verbose,
            f"sync {src} {dest_dir}/",
            lambda cb: self._s3().sync(src, f"{dest_dir}/", on_result=cb),
        )

    def put_text(self, rel_key: str, text: str, *, verbose: bool = False) -> None:
        import io

        from boto3_s3 import IOStorage

        if verbose:
            write_stderr(f"+ (boto3-s3) cp - {self._s3_url(rel_key)}\n")
        self._s3().cp(IOStorage(io.BytesIO(text.encode("utf-8"))), self._s3_url(rel_key))

    def put_object(
        self,
        rel_key: str,
        src_path: str,
        *,
        verbose: bool = False,
        metadata: dict[str, str] | None = None,
    ) -> TransferResult:
        dst = self._s3_url(rel_key)
        options: dict[str, Any] = {"metadata": metadata} if metadata else {}
        return self._transfer(
            verbose,
            f"cp {src_path} {dst}",
            lambda cb: self._s3().cp(src_path, dst, on_result=cb, **options),
        )

    def sync_up(
        self,
        src_dir: str,
        rel_prefix: str,
        *,
        excludes: list[str],
        delete: bool = False,
        dryrun: bool = False,
        verbose: bool = False,
    ) -> TransferResult:
        dst = f"{self._s3_url(rel_prefix)}/" if rel_prefix else f"{self.prefix}/"
        filt = None
        if excludes:
            from boto3_s3 import GlobFilter

            filt = GlobFilter().exclude(*excludes).compile()
        return self._transfer(
            verbose,
            f"sync {src_dir} {dst}",
            # follow_symlinks=False: symlinks are not uploaded as data; the
            # manifest records them and apply_manifest recreates them on restore.
            lambda cb: self._s3().sync(
                src_dir,
                dst,
                delete=delete,
                dryrun=dryrun,
                filter=filt,
                follow_symlinks=False,
                on_result=cb,
            ),
        )


# =============================================================================
# Exclude pattern matching (find -path semantics: * matches /)
# =============================================================================

_pattern_cache: dict[str, re.Pattern[str]] = {}


def _glob_to_regex(pattern: str) -> str:
    result: list[str] = []
    i = 0
    while i < len(pattern):
        c = pattern[i]
        if c == "*":
            result.append(".*")
        elif c == "?":
            result.append(".")
        elif c == "[":
            j = i + 1
            if j < len(pattern) and pattern[j] in "!^":
                j += 1
            if j < len(pattern) and pattern[j] == "]":
                j += 1
            while j < len(pattern) and pattern[j] != "]":
                j += 1
            result.append(pattern[i : j + 1])
            i = j
        else:
            result.append(re.escape(c))
        i += 1
    return "".join(result)


def path_match(path: str, pattern: str) -> bool:
    if pattern not in _pattern_cache:
        _pattern_cache[pattern] = re.compile(_glob_to_regex(pattern))
    return _pattern_cache[pattern].fullmatch(path) is not None


def _split_excludes(excludes: list[str]) -> tuple[list[str], list[str]]:
    prune_patterns: list[str] = []
    skip_patterns: list[str] = []
    for ex in excludes:
        if ex.endswith("/*"):
            prune_patterns.append(f"./{ex[:-2]}")
        else:
            skip_patterns.append(f"./{ex}")
    return prune_patterns, skip_patterns


# =============================================================================
# Tree iteration
# =============================================================================


def iter_tree(root: str, excludes: list[str]) -> Iterator[tuple[str, os.stat_result, str | None]]:
    """Walk directory tree yielding (rel, lstat_result, symlink_target|None).

    rel uses "./" prefix (e.g., ".", "./sub/file").
    """
    prune_patterns, skip_patterns = _split_excludes(excludes)

    st = os.lstat(root)
    yield ".", st, None

    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        rel_dir = os.path.relpath(dirpath, root)
        rel_prefix = "./" if rel_dir == "." else f"./{rel_dir}/"

        dirnames.sort()
        filenames.sort()

        to_remove: list[str] = []
        for d in dirnames:
            rel = f"{rel_prefix}{d}"
            if any(path_match(rel, p) for p in prune_patterns):
                to_remove.append(d)
                continue
            full = os.path.join(dirpath, d)
            st = os.lstat(full)
            if stat_mod.S_ISLNK(st.st_mode):
                yield rel, st, os.readlink(full)
                to_remove.append(d)
            else:
                yield rel, st, None
        for d in to_remove:
            dirnames.remove(d)

        for f in filenames:
            rel = f"{rel_prefix}{f}"
            if any(path_match(rel, p) for p in skip_patterns):
                continue
            full = os.path.join(dirpath, f)
            st = os.lstat(full)
            if stat_mod.S_ISLNK(st.st_mode):
                yield rel, st, os.readlink(full)
            else:
                yield rel, st, None


def iter_local_tree(outpath: str, excludes: list[str]) -> Iterator[tuple[str, bool]]:
    """Walk local tree yielding (rel_without_dot_slash, is_dir)."""
    prune_patterns, skip_patterns = _split_excludes(excludes)

    for dirpath, dirnames, filenames in os.walk(outpath, followlinks=False):
        rel_dir = os.path.relpath(dirpath, outpath)
        rel_prefix = "./" if rel_dir == "." else f"./{rel_dir}/"

        dirnames.sort()
        filenames.sort()

        to_remove: list[str] = []
        for d in dirnames:
            rel = f"{rel_prefix}{d}"
            if any(path_match(rel, p) for p in prune_patterns):
                to_remove.append(d)
                continue
            yield rel[2:], True  # strip "./"
        for d in to_remove:
            dirnames.remove(d)

        for f in filenames:
            rel = f"{rel_prefix}{f}"
            if any(path_match(rel, p) for p in skip_patterns):
                continue
            yield rel[2:], False


# =============================================================================
# Manifest generation
# =============================================================================


def format_stat_line(rel: str, st: os.stat_result, sym_target: str | None) -> str:
    """Format like: stat -c '%a %U %G %s %y %N' with QUOTING_STYLE=shell-always."""
    mode = format(stat_mod.S_IMODE(st.st_mode), "o")

    if pwd is not None:
        try:
            owner = pwd.getpwuid(st.st_uid).pw_name
        except KeyError:
            owner = str(st.st_uid)
    else:
        owner = str(st.st_uid)
    if grp is not None:
        try:
            group = grp.getgrgid(st.st_gid).gr_name
        except KeyError:
            group = str(st.st_gid)
    else:
        group = str(st.st_gid)

    size = st.st_size

    epoch_sec = st.st_mtime_ns // 1_000_000_000
    nsec = st.st_mtime_ns % 1_000_000_000
    dt = datetime.datetime.fromtimestamp(epoch_sec, tz=datetime.timezone.utc).astimezone()
    utc_off = dt.utcoffset()
    assert utc_off is not None
    total_sec = int(utc_off.total_seconds())
    sign = "+" if total_sec >= 0 else "-"
    total_sec = abs(total_sec)
    h, rem = divmod(total_sec, 3600)
    m = rem // 60
    mtime_str = f"{dt.strftime('%Y-%m-%d %H:%M:%S')}.{nsec:09d} {sign}{h:02d}{m:02d}"

    if sym_target is not None:
        name_field = f"{shell_always_quote(rel)} -> {shell_always_quote(sym_target)}"
    else:
        name_field = shell_always_quote(rel)

    return f"{mode} {owner} {group} {size} {mtime_str} {name_field}"


def write_manifest_to_aws(
    cfg: Config, entry: str, target: str, excludes: list[str], verbose: bool
) -> None:
    entrylist = f"{entry}-ls-l.txt"
    write_stderr(f"Updating {cfg.prefix}/{entrylist}\n")

    lines: list[str] = []
    if os.path.isdir(target):
        for rel, st, sym_target in iter_tree(target, excludes):
            lines.append(format_stat_line(rel, st, sym_target))
    else:
        basename = os.path.basename(target)
        st = os.lstat(target)
        sym = os.readlink(target) if stat_mod.S_ISLNK(st.st_mode) else None
        lines.append(format_stat_line(basename, st, sym))

    manifest_data = "\n".join(lines) + "\n" if lines else ""
    assert cfg.store is not None
    cfg.store.put_text(entrylist, manifest_data, verbose=verbose)


def upload_manifest(cfg: Config, entry: str, target: str, excludes: list[str], opts: Opts) -> int:
    post_hook: str | None = cfg.entries[entry].get("post_hook")

    if opts.dryrun:
        print(f"(dryrun) would update manifest: {entry}-ls-l.txt")
        if post_hook:
            print(f"(dryrun) would run post_hook: {post_hook}")
        return 0

    write_manifest_to_aws(cfg, entry, target, excludes, opts.verbose)

    if post_hook:
        if opts.verbose:
            write_stderr(f"+ {post_hook}\n")
        subprocess.run(["bash", "-c", post_hook])

    return 0


def _manifest_line_key(line: str) -> str:
    entry = parse_manifest_line(line)
    return "" if entry is None else entry.rel.removeprefix("./")


def _iter_sub_tree_lines(local_sub: str, sub: str, excludes: list[str]) -> Iterator[str]:
    st = os.lstat(local_sub)
    if stat_mod.S_ISLNK(st.st_mode):
        sym = os.readlink(local_sub)
        yield format_stat_line(f"./{sub}", st, sym)
        return
    if not os.path.isdir(local_sub):
        yield format_stat_line(f"./{sub}", st, None)
        return
    for rel, st2, sym_target in iter_tree(local_sub, excludes):
        if rel == ".":
            disp = f"./{sub}"
        else:
            tail = rel[2:]
            disp = f"./{sub}/{tail}"
        yield format_stat_line(disp, st2, sym_target)


def patch_manifest_subtree(
    cfg: Config,
    entry: str,
    target_root: str,
    sub: str,
    excludes: list[str],
    opts: Opts,
) -> None:
    """Download the manifest, replace the lines under `sub`, and re-upload it.

    target_root/sub may be a file, a symlink, or a directory.
    If it does not exist, the lines under that `sub` are simply removed.
    """
    entrylist = f"{entry}-ls-l.txt"
    if opts.dryrun:
        print(f"(dryrun) would patch manifest: {entrylist} (sub={sub})")
        return

    fd, manifest_path = tempfile.mkstemp(suffix=".txt")
    os.close(fd)
    try:
        existing: list[str] = []
        if download_manifest(cfg, entry, manifest_path, opts.verbose):
            with open(manifest_path) as f:
                for line in f:
                    line = line.rstrip("\n")
                    if line:
                        existing.append(line)

        kept: list[str] = []
        for line in existing:
            entry_obj = parse_manifest_line(line)
            if entry_obj is None:
                kept.append(line)
                continue
            rel = entry_obj.rel.removeprefix("./")
            if rel == sub or rel.startswith(sub + "/"):
                continue
            kept.append(line)

        new_lines: list[str] = []
        local_sub = os.path.join(target_root, sub)
        if os.path.lexists(local_sub):
            new_lines = list(_iter_sub_tree_lines(local_sub, sub, excludes))

        merged = kept + new_lines
        merged.sort(key=_manifest_line_key)

        data = "\n".join(merged) + "\n" if merged else ""
        write_stderr(f"Updating {cfg.prefix}/{entrylist}\n")
        assert cfg.store is not None
        cfg.store.put_text(entrylist, data, verbose=opts.verbose)
    finally:
        os.unlink(manifest_path)


# =============================================================================
# Manifest application (restore metadata)
# =============================================================================


def _windows_collect_writable_prep(
    outpath: str, is_dir: bool, manifest_path: str, sub: str | None
) -> list[tuple[str, int]]:
    # Windows only. Walk the manifest, find existing local files that are:
    #   - regular files (not dir / not symlink)
    #   - read-only (owner write bit clear)
    #   - differ from the manifest in size or mtime
    # Temporarily add owner-write so `boto3-s3 sync`/`cp` can overwrite them.
    # Returns [(path, original_mode), ...] for later restoration.
    targets: list[tuple[str, int]] = []
    try:
        for entry in iter_manifest(manifest_path):
            if entry.sym_target is not None:
                continue
            res = manifest_target(entry, outpath, is_dir, sub)
            if res is None:
                continue
            target, _rel = res
            try:
                st = os.lstat(target)
            except OSError:
                continue
            if not stat_mod.S_ISREG(st.st_mode):
                continue
            if st.st_mode & stat_mod.S_IWRITE:
                continue
            try:
                size = entry.size_int
            except ValueError:
                size = -1
            differs = size < 0 or st.st_size != size
            if not differs:
                try:
                    differs = int(st.st_mtime) != entry.epoch
                except (ValueError, OSError):
                    differs = True
            if not differs:
                continue
            try:
                os.chmod(target, st.st_mode | stat_mod.S_IWRITE)
            except OSError:
                continue
            targets.append((target, st.st_mode))
    except OSError:
        pass
    return targets


def _windows_restore_modes(targets: list[tuple[str, int]]) -> None:
    for target, original_mode in targets:
        try:
            os.chmod(target, original_mode)
        except OSError:
            continue


def _apply_meta(target: str, mode: int, epoch: float) -> bool:
    ok = True
    try:
        os.utime(target, (epoch, epoch))
    except PermissionError as e:
        err(f"utime failed (not owner?): {target}: {e}")
        ok = False
    try:
        os.chmod(target, mode)
    except PermissionError as e:
        err(f"chmod failed (not owner?): {target}: {e}")
        ok = False
    return ok


def apply_manifest(
    cfg: Config,
    entry: str,
    outpath: str,
    is_dir: bool,
    manifest_path: str,
    sub: str | None = None,
    verbose: bool = False,
) -> int:
    remote_keys: set[str] = set()
    if is_dir:
        assert cfg.store is not None
        all_keys = cfg.store.list_keys_under(entry, verbose=verbose)
        if sub is not None:
            sub_prefix = sub + "/"
            for k in all_keys:
                if k.startswith(sub_prefix):
                    remote_keys.add(k[len(sub_prefix) :])
        else:
            remote_keys = all_keys

    deferred_dirs: list[tuple[str, int, float]] = []
    errors = 0

    for m_entry in iter_manifest(manifest_path):
        res = manifest_target(m_entry, outpath, is_dir, sub)
        if res is None:
            continue
        target, rel = res
        epoch = parse_timestamp(m_entry.date_str, m_entry.time_str, m_entry.zone_str)
        mode = m_entry.mode_int

        if m_entry.sym_target is not None:
            parent = os.path.dirname(target)
            if parent:
                os.makedirs(parent, exist_ok=True)
            # Clear whatever is already there. islink first, so a symlink is
            # removed as a link (never recursing into its target); a real dir
            # (e.g. left by an older follow-symlinks backup) is removed wholesale.
            if os.path.islink(target) or os.path.isfile(target):
                os.remove(target)
            elif os.path.isdir(target):
                shutil.rmtree(target)
            os.symlink(m_entry.sym_target, target)
            write_output(f"{target} -> {m_entry.sym_target}\n")
            continue

        if not is_dir:
            kind = "file"
        elif rel == ".":
            kind = "dir"
        elif rel in remote_keys:
            kind = "file"
        else:
            kind = "dir"

        if kind == "dir":
            if not os.path.exists(target):
                os.makedirs(target, exist_ok=True)
            deferred_dirs.append((target, mode, epoch))
            continue

        if not os.path.exists(target):
            err(f"expected file missing (sync did not place it): {target}")
            errors += 1
            continue

        write_output(f"{m_entry.mode_str} {target}\n")
        if not _apply_meta(target, mode, epoch):
            errors += 1

    deferred_dirs.sort(key=lambda x: x[0], reverse=True)
    for target, mode, epoch in deferred_dirs:
        write_output(f"{format(mode, 'o')} {target}\n")
        if not _apply_meta(target, mode, epoch):
            errors += 1

    return 1 if errors else 0


# =============================================================================
# S3 download helpers
# =============================================================================


def download_manifest(cfg: Config, entry: str, dest: str, verbose: bool = False) -> bool:
    assert cfg.store is not None
    return cfg.store.get_object(
        f"{entry}-ls-l.txt",
        dest,
        verbose=verbose,
        check=False,
    )


def _print_transfer_lines(stdout: str) -> bool:
    """Print the transfer-result lines, skipping progress noise. Returns True
    if any transfer line was printed.
    """
    if not stdout:
        return False
    changed = False
    for line in stdout.replace("\r", "\n").splitlines():
        line = line.strip()
        if (
            line
            and not line.startswith("Completed ")
            and not line.startswith("warning: Skipping file")
        ):
            changed = True
            write_output(f"{line}\n")
    return changed


def download_from_s3(
    cfg: Config,
    entry: str,
    outpath: str,
    is_dir: bool,
    verbose: bool,
    sub: str | None = None,
) -> tuple[int, bool]:
    assert cfg.store is not None
    rel = f"{entry}/{sub}" if sub else entry

    if is_dir:
        result = cfg.store.sync_down(rel, outpath, verbose=verbose)
        if result.returncode != 0:
            if result.stderr:
                write_stderr(result.stderr)
            return result.returncode, False
        return 0, _print_transfer_lines(result.stdout)

    # Single file: cp always transfers (we only reach here on a manifest
    # mismatch), so a successful download counts as changed -> apply_manifest
    # runs and restores mode/mtime. Matters on Windows, where apply_manifest is
    # skipped when nothing changed.
    parent = os.path.dirname(outpath)
    if parent:
        os.makedirs(parent, exist_ok=True)
    if not cfg.store.get_object(rel, outpath, verbose=verbose):
        return 1, False
    return 0, True


# =============================================================================
# delete_extra_files
# =============================================================================


def delete_extra_files(
    outpath: str,
    check_only: bool,
    remote_files: dict[str, int],
    excludes: list[str],
) -> bool:
    extras: list[tuple[str, bool]] = []
    for rel, is_dir_entry in iter_local_tree(outpath, excludes):
        if not rel or rel == ".":
            continue
        if rel not in remote_files:
            extras.append((os.path.join(outpath, rel), is_dir_entry))

    if not extras:
        return False

    extras.sort(key=lambda x: x[0], reverse=True)

    for path, is_dir_entry in extras:
        if check_only:
            write_output(f"A {path}\n")
        else:
            try:
                if is_dir_entry:
                    os.rmdir(path)
                else:
                    os.remove(path)
                write_output(f"delete: {path}\n")
            except OSError:
                pass

    return True


# =============================================================================
# Commands
# =============================================================================


def _filter_aws_output(raw: str) -> str:
    filtered: list[str] = []
    for line in raw.replace("\r", "\n").splitlines():
        line = line.strip()
        if (
            line
            and not line.startswith("Completed ")
            and not line.startswith("warning: Skipping file")
        ):
            filtered.append(line)
    return "\n".join(filtered)


def _run_post_hook(post_hook: str | None, opts: Opts) -> None:
    if not post_hook:
        return
    if opts.dryrun:
        print(f"(dryrun) would run post_hook: {post_hook}")
        return
    if opts.verbose:
        write_stderr(f"+ {post_hook}\n")
    _ = subprocess.run(["bash", "-c", post_hook])


def _push_sub(
    cfg: Config,
    entry: str,
    post_hook: str | None,
    target_root: str,
    sub: str,
    excludes: list[str],
    opts: Opts,
) -> int:
    local_sub = os.path.join(target_root, sub)
    sub_rel = f"{entry}/{sub}"
    s3_sub_path = f"{cfg.prefix}/{sub_rel}"

    if not os.path.lexists(local_sub):
        err(f"local path does not exist: {local_sub}")
        return 1

    if opts.meta_only:
        patch_manifest_subtree(cfg, entry, target_root, sub, excludes, opts)
        _run_post_hook(post_hook, opts)
        return 0

    assert cfg.store is not None
    st = os.lstat(local_sub)

    if stat_mod.S_ISLNK(st.st_mode):
        # symlink: upload nothing, just update manifest line.
        pass
    elif os.path.isdir(local_sub):
        result = cfg.store.sync_up(
            local_sub,
            sub_rel,
            excludes=excludes,
            delete=opts.delete,
            dryrun=opts.dryrun,
            verbose=opts.verbose,
        )
        if result.returncode != 0:
            write_output(result.stdout)
            if result.stderr:
                write_stderr(result.stderr)
            return result.returncode
        filtered = _filter_aws_output(result.stdout)
        if filtered:
            write_output(f"{filtered}\n")
    else:
        # Regular file.
        local_mtime = str(int(os.path.getmtime(local_sub)))
        if opts.dryrun:
            msg = f"(dryrun) upload: {local_sub} -> {s3_sub_path}"
            print(msg)
        else:
            result = cfg.store.put_object(
                sub_rel,
                local_sub,
                verbose=opts.verbose,
                metadata={"local-mtime": local_mtime},
            )
            if result.returncode != 0:
                write_output(result.stdout)
                if result.stderr:
                    write_stderr(result.stderr)
                return result.returncode
            filtered = _filter_aws_output(result.stdout)
            if filtered:
                write_output(f"{filtered}\n")

    if not opts.data_only:
        patch_manifest_subtree(cfg, entry, target_root, sub, excludes, opts)
    _run_post_hook(post_hook, opts)
    return 0


def cmd_push(cfg: Config, entry: str, opts: Opts, sub: str | None = None) -> int:
    entry_cfg = cfg.entries.get(entry)
    if not entry_cfg:
        err(f"no such entry: {entry}")
        return 1
    target: str = entry_cfg["path"]
    target_root = _normalize_local_path(target)
    if sub is None and not os.path.exists(target):
        err(f"target does not exist: {target}")
        return 1

    excludes: list[str] = entry_cfg.get("excludes", [])

    pre_hook: str | None = entry_cfg.get("pre_hook")
    if pre_hook:
        if opts.dryrun:
            print(f"(dryrun) would run pre_hook: {pre_hook}")
        else:
            if opts.verbose:
                write_stderr(f"+ {pre_hook}\n")
            st = subprocess.run(["bash", "-c", pre_hook]).returncode
            if st != 0:
                return st

    if sub is not None:
        post_hook_sub: str | None = entry_cfg.get("post_hook")
        return _push_sub(cfg, entry, post_hook_sub, target_root, sub, excludes, opts)

    if entry.endswith(".git") and opts.meta_only:
        err(f"skipping manifest for {entry} (.git suffix convention)")
        return 0

    if opts.meta_only:
        return upload_manifest(cfg, entry, target, excludes, opts)

    results = ""
    assert cfg.store is not None

    if os.path.isdir(target):
        result = cfg.store.sync_up(
            target,
            entry,
            excludes=excludes,
            delete=True,
            dryrun=opts.dryrun,
            verbose=opts.verbose,
        )
        if result.returncode != 0:
            write_output(result.stdout)
            if result.stderr:
                write_stderr(result.stderr)
            return result.returncode
        results = _filter_aws_output(result.stdout)
    else:
        local_mtime = str(int(os.path.getmtime(target)))
        head = cfg.store.head_object(entry, verbose=opts.verbose)
        s3_local_mtime = head.metadata.get("local-mtime", "") if head else ""

        if local_mtime != s3_local_mtime:
            if opts.dryrun:
                msg = f"(dryrun) upload: {target} -> {cfg.prefix}/{entry}"
                print(msg)
                results = msg
            else:
                result = cfg.store.put_object(
                    entry,
                    target,
                    verbose=opts.verbose,
                    metadata={"local-mtime": local_mtime},
                )
                if result.returncode != 0:
                    write_output(result.stdout)
                    if result.stderr:
                        write_stderr(result.stderr)
                    return result.returncode
                results = _filter_aws_output(result.stdout)

    if results:
        write_output(f"{results}\n")

    if results and not opts.data_only:
        try:
            upload_manifest(cfg, entry, target, excludes, opts)
        except subprocess.CalledProcessError as e:
            return e.returncode

    if results and opts.data_only:
        post_hook: str | None = entry_cfg.get("post_hook")
        _run_post_hook(post_hook, opts)

    return 0


def _sub_remote_kind(cfg: Config, entry: str, sub: str, verbose: bool = False) -> str:
    """Return "file", "dir", or "missing" for <entry>/<sub> on S3."""
    assert cfg.store is not None
    if cfg.store.head_object(f"{entry}/{sub}", verbose=verbose) is not None:
        return "file"
    prefix = sub + "/"
    for k in cfg.store.list_keys_under(entry, verbose=verbose):
        if k.startswith(prefix):
            return "dir"
    return "missing"


def _entry_kind_from_manifest(manifest_path: str) -> str:
    """Return 'dir' or 'file' from manifest content.

    write_manifest_to_aws emits './...' relative paths for directories
    (always starting with a '.' entry) and a bare basename for single files.
    Returns 'file' for empty/malformed manifests so callers fail fast.
    """
    for entry in iter_manifest(manifest_path):
        return "dir" if entry.rel == "." or entry.rel.startswith("./") else "file"
    return "file"


def _sub_kind_from_manifest(manifest_path: str, sub: str) -> str:
    """Return 'file', 'dir', or 'missing' for sub by scanning manifest only.

    Empty directories cannot be distinguished from files here (manifest
    drops type bits); callers should treat 'file' as ambiguous and confirm
    with a head-object when needed.
    """
    found_self = False
    for entry in iter_manifest(manifest_path):
        rel = entry.rel.removeprefix("./")
        if rel == sub:
            found_self = True
        elif rel.startswith(sub + "/"):
            return "dir"
    return "file" if found_self else "missing"


def _manifest_matches_local(
    manifest_path: str, outpath: str, is_dir: bool, sub: str | None
) -> bool:
    """True iff every manifest entry matches the local filesystem.

    Returning True means 'boto3-s3 sync' would copy nothing AND apply_manifest
    would change nothing - so both can be skipped.
    """
    for entry in iter_manifest(manifest_path):
        res = manifest_target(entry, outpath, is_dir, sub)
        if res is None:
            continue
        target, _rel = res
        if not compare_to_local(entry, target).is_match:
            return False
    return True


def cmd_pull(cfg: Config, entry: str, opts: Opts, sub: str | None = None) -> int:
    outpath: str | None = opts.outpath
    entry_cfg = cfg.entries.get(entry)
    if outpath is None:
        if not entry_cfg:
            err(f"no such entry in config: {entry}")
            err("use -o <path> to specify the output path")
            return 1
        base_path: str = entry_cfg["path"]
        outpath = os.path.join(base_path, sub) if sub else base_path

    if outpath.endswith("/"):
        tail = sub if sub else entry
        outpath = os.path.join(outpath, tail)

    fd, manifest_path = tempfile.mkstemp(suffix=".txt")
    os.close(fd)
    try:
        # 1. Fetch the manifest first; its content tells us file/dir
        #    without any extra head-object calls.
        if not download_manifest(cfg, entry, manifest_path, opts.verbose):
            if sub is not None:
                err(f"not found on S3: {entry}/{sub}")
            else:
                err(f"entry not found on S3: {entry}")
            return 1

        entry_is_dir = _entry_kind_from_manifest(manifest_path) == "dir"

        if sub is not None:
            if not entry_is_dir:
                err(f"sub path not allowed for single-file entry: {entry}")
                return 1
            kind = _sub_kind_from_manifest(manifest_path, sub)
            if kind == "missing":
                err(f"not found on S3: {entry}/{sub}")
                return 1
            is_dir = kind == "dir"
        else:
            is_dir = entry_is_dir

        # 2. If everything in the manifest already matches local, both
        #    the s3 sync/cp and apply_manifest are no-ops. Skip them.
        if _manifest_matches_local(manifest_path, outpath, is_dir, sub):
            if not opts.meta_only and opts.delete and is_dir:
                excludes: list[str] = entry_cfg.get("excludes", []) if entry_cfg else []
                remote_files = _read_manifest_files(manifest_path, sub=sub)
                delete_extra_files(outpath, False, remote_files, excludes)
            return 0

        # 3. Normal path: prep, then sync (dir) or cp (file).
        prep: list[tuple[str, int]] = []
        if IS_WINDOWS and not opts.meta_only:
            prep = _windows_collect_writable_prep(outpath, is_dir, manifest_path, sub)

        sync_changed = False
        if not opts.meta_only:
            rc, sync_changed = download_from_s3(cfg, entry, outpath, is_dir, opts.verbose, sub=sub)
            if rc != 0:
                if IS_WINDOWS:
                    _windows_restore_modes(prep)
                return rc

        # 4. Apply manifest metadata (mode, mtime, symlinks).
        #    Skipped entirely with --data-only.
        if opts.data_only:
            if IS_WINDOWS and not opts.meta_only:
                _windows_restore_modes(prep)
            st = 0
        elif IS_WINDOWS and not opts.meta_only and not sync_changed:
            _windows_restore_modes(prep)
            st = 0
        else:
            st = apply_manifest(
                cfg,
                entry,
                outpath,
                is_dir,
                manifest_path,
                sub=sub,
                verbose=opts.verbose,
            )

        if not opts.meta_only and opts.delete and is_dir:
            excludes = entry_cfg.get("excludes", []) if entry_cfg else []
            remote_files = _read_manifest_files(manifest_path, sub=sub)
            delete_extra_files(outpath, False, remote_files, excludes)

        return st
    finally:
        os.unlink(manifest_path)


def _read_manifest_files(manifest_path: str, sub: str | None = None) -> dict[str, int]:
    remote_files: dict[str, int] = {}
    for entry in iter_manifest(manifest_path):
        rel = entry.rel.removeprefix("./")
        if sub is not None:
            if rel == sub:
                continue
            if not rel.startswith(sub + "/"):
                continue
            rel = rel[len(sub) + 1 :]
        remote_files[rel] = 1
    return remote_files


def cmd_show(cfg: Config, entry: str, opts: Opts, file: str | None = None) -> int:
    if entry not in cfg.entries:
        err(f"no such entry: {entry}")
        return 1

    if file:
        file = file.lstrip("./")
        rel = f"{entry}/{file}"
    else:
        rel = entry

    assert cfg.store is not None
    return cfg.store.stream_object_to_stdout(rel, verbose=opts.verbose)


_ANSI_GREEN = "\033[1;32m"
_ANSI_RESET = "\033[0m"


def _resolve_use_color(mode: str) -> bool:
    if mode == "always":
        return True
    if mode == "never":
        return False
    if os.environ.get("NO_COLOR"):
        return False
    try:
        return sys.stdout.isatty()
    except (AttributeError, ValueError):
        return False


def _color_wrap(s: str, use_color: bool) -> str:
    return f"{_ANSI_GREEN}{s}{_ANSI_RESET}" if use_color else s


def _diff_color_flag(color_mode: str) -> str:
    return f"--color={'always' if _resolve_use_color(color_mode) else 'never'}"


def _humanize_size_diff(diff_bytes: int) -> str:
    diff = abs(diff_bytes)
    if diff < 1024:
        return f"+{diff} bytes"
    for unit, threshold in (
        ("TB", 1024**4),
        ("GB", 1024**3),
        ("MB", 1024**2),
        ("KB", 1024),
    ):
        if diff >= threshold:
            return f"+{diff} bytes (+{diff / threshold:.2f} {unit})"
    return f"+{diff} bytes"


def _humanize_duration(diff_sec: int) -> str:
    diff = abs(diff_sec)
    if diff == 0:
        return "+0s"
    days, rem = divmod(diff, 86400)
    hours, rem = divmod(rem, 3600)
    minutes, seconds = divmod(rem, 60)
    parts: list[str] = []
    if days:
        parts.append(f"{days}d")
    if hours:
        parts.append(f"{hours}h")
    if minutes:
        parts.append(f"{minutes}m")
    if seconds:
        parts.append(f"{seconds}s")
    return "+" + " ".join(parts[:2])


def format_diff_block(diff: EntryDiff, target: str, verbose: bool) -> str | None:
    if diff.is_match:
        return None
    if diff.status == "D":
        block = f"D {target}\n"
    else:
        block = f"M {target}\t{', '.join(diff.tags)}\n"
    if verbose:
        for d in diff.details:
            block += f"      {d}\n"
    return block


def check_metadata(
    target: str,
    entry: ManifestEntry,
    verbose: bool,
    use_color: bool = False,
    ignore_dir_mtime: bool = False,
) -> str | None:
    diff = compare_to_local(entry, target, use_color=use_color, ignore_dir_mtime=ignore_dir_mtime)
    return format_diff_block(diff, target, verbose)


def cmd_status(cfg: Config, entry: str, opts: Opts, sub: str | None = None) -> int:
    entry_cfg = cfg.entries.get(entry)
    if not entry_cfg:
        err(f"no such entry: {entry}")
        return 1
    base_path: str = entry_cfg["path"]
    outpath = os.path.join(base_path, sub) if sub else base_path

    fd, manifest_path = tempfile.mkstemp(suffix=".txt")
    os.close(fd)
    try:
        if not download_manifest(cfg, entry, manifest_path, opts.verbose):
            return 1

        is_dir = os.path.isdir(outpath)
        excludes: list[str] = entry_cfg.get("excludes", [])
        use_color = _resolve_use_color(opts.color)

        remote_files: dict[str, int] = {}
        for entry_obj in iter_manifest(manifest_path):
            res = manifest_target(entry_obj, outpath, is_dir, sub)
            if res is None:
                continue
            target, rel = res
            if is_dir:
                remote_files[rel] = 1
            block = check_metadata(
                target,
                entry_obj,
                opts.verbose,
                use_color=use_color,
                ignore_dir_mtime=True,
            )
            if block:
                write_output(block)

        if is_dir:
            delete_extra_files(outpath, True, remote_files, excludes)

        return 0
    finally:
        os.unlink(manifest_path)


def diff_single_file(cfg: Config, rel_key: str, label: str, localfile: str, opts: Opts) -> int:
    fd, tmppath = tempfile.mkstemp()
    os.close(fd)
    try:
        assert cfg.store is not None
        if not cfg.store.get_object(rel_key, tmppath, verbose=opts.verbose, check=True):
            return 1
        cmd = [
            "diff",
            _diff_color_flag(opts.color),
            "-ru",
            tmppath,
            localfile,
            "--label",
            f"a/{label}",
            "--label",
            f"b/{label}",
        ]
        echo_command(opts.verbose, cmd)
        result = subprocess.run(cmd)
        return 0 if result.returncode == 0 else 1
    finally:
        os.unlink(tmppath)


def diff_backup(cfg: Config, entry: str, outpath: str, opts: Opts) -> int:
    excludes: list[str] = cfg.entries[entry].get("excludes", [])
    tmpdir = tempfile.mkdtemp()
    has_diff = 0

    try:
        assert cfg.store is not None
        result = cfg.store.sync_down(entry, tmpdir, verbose=opts.verbose)
        if result.returncode != 0:
            if result.stderr:
                write_stderr(result.stderr)
            return result.returncode

        backup_files: set[str] = set()
        for dirpath, _, filenames in os.walk(tmpdir):
            for f in sorted(filenames):
                full = os.path.join(dirpath, f)
                rel = os.path.relpath(full, tmpdir)
                backup_files.add(rel)
                local = os.path.join(outpath, rel)
                if not os.path.exists(local):
                    cmd = [
                        "diff",
                        _diff_color_flag(opts.color),
                        "-u",
                        full,
                        "/dev/null",
                        "--label",
                        f"a/{rel}",
                        "--label",
                        f"b/{rel}",
                    ]
                    echo_command(opts.verbose, cmd)
                    subprocess.run(cmd)
                    has_diff = 1
                    continue
                cmd = [
                    "diff",
                    _diff_color_flag(opts.color),
                    "-u",
                    full,
                    local,
                    "--label",
                    f"a/{rel}",
                    "--label",
                    f"b/{rel}",
                ]
                echo_command(opts.verbose, cmd)
                r = subprocess.run(cmd)
                if r.returncode != 0:
                    has_diff = 1

        for rel, is_dir_entry in iter_local_tree(outpath, excludes):
            if is_dir_entry:
                continue
            if not os.path.isfile(os.path.join(outpath, rel)):
                continue
            if rel in backup_files:
                continue
            cmd = [
                "diff",
                _diff_color_flag(opts.color),
                "-u",
                "/dev/null",
                os.path.join(outpath, rel),
                "--label",
                f"a/{rel}",
                "--label",
                f"b/{rel}",
            ]
            echo_command(opts.verbose, cmd)
            subprocess.run(cmd)
            has_diff = 1

        return has_diff
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


def cmd_diff(cfg: Config, entry: str, opts: Opts, file: str | None = None) -> int:
    entry_cfg = cfg.entries.get(entry)
    if not entry_cfg:
        err(f"no such entry: {entry}")
        return 1
    outpath: str = entry_cfg["path"]

    if file:
        file = file.lstrip("./")
        return diff_single_file(
            cfg,
            f"{entry}/{file}",
            f"{entry}/{file}",
            f"{outpath}/{file}",
            opts,
        )

    is_dir = os.path.isdir(outpath)
    if not is_dir:
        return diff_single_file(cfg, entry, entry, outpath, opts)

    return diff_backup(cfg, entry, outpath, opts)


def cmd_list(cfg: Config, opts: Opts) -> int:
    for key in sorted(cfg.entries.keys()):
        path = cfg.entries[key]["path"]
        write_output(f"{key:<20s} {path}\n")
    return 0


def show_entry_files(manifest_path: str, sub: str | None = None) -> None:
    for entry in iter_manifest(manifest_path):
        if sub is not None:
            rel = entry.rel.removeprefix("./")
            if rel != sub and not rel.startswith(sub + "/"):
                continue
        display = entry.rel
        if entry.sym_target:
            display = f"{entry.rel} -> {entry.sym_target}"
        time_str = entry.time_str.split(".")[0]
        write_output(
            f"{entry.mode_str:<4s} {entry.user:<8s} {entry.group:<8s} "
            f"{entry.size_str:>8s}  {entry.date_str} {time_str}  {display}\n"
        )


def cmd_ls_remote(cfg: Config, opts: Opts, entry: str | None = None, sub: str | None = None) -> int:
    assert cfg.store is not None
    if entry is None:
        for line in cfg.store.list_top_level_lines(verbose=opts.verbose):
            if line.endswith("-ls-l.txt"):
                parts = line.split()
                if parts:
                    name = parts[-1].removesuffix("-ls-l.txt")
                    write_output(f"{name}\n")
        return 0

    if entry not in cfg.entries:
        err(f"no such entry: {entry}")
        return 1

    fd, manifest_path = tempfile.mkstemp(suffix=".txt")
    os.close(fd)
    try:
        if not download_manifest(cfg, entry, manifest_path, opts.verbose):
            return 1
        show_entry_files(manifest_path, sub=sub)
        return 0
    finally:
        os.unlink(manifest_path)


# =============================================================================
# Parallel runner
# =============================================================================


def run_entries(
    fn: Callable[[Config, str, Opts], int],
    cfg: Config,
    entries: list[str],
    opts: Opts,
) -> int:
    if not entries:
        return 0
    if len(entries) == 1:
        return fn(cfg, entries[0], opts)

    agg = 0
    with concurrent.futures.ThreadPoolExecutor(max_workers=len(entries)) as executor:
        futures = {executor.submit(fn, cfg, e, opts): e for e in entries}
        for future in concurrent.futures.as_completed(futures):
            try:
                st = future.result()
                if st and not agg:
                    agg = st
            except Exception as exc:
                entry = futures[future]
                err(f"{entry}: {exc}")
                if not agg:
                    agg = 1
    return agg


# =============================================================================
# Usage
# =============================================================================


def print_usage(status: int = 1) -> NoReturn:
    config_path = os.environ.get("S3BAK_CONFIG") or expand_home("~/.config/s3bak/config.py")
    text = f"""\
Usage: s3bak <command> [options] [args]

Commands:
  push <entry|path>...         Back up entries or sub-paths to S3
  pull <entry|path>            Restore an entry or sub-path (use --all for every entry)
  show <entry|path>            Print a single file from the backup to stdout
  status <entry|path>...       Compare local vs backup (metadata only)
  diff <entry|path>            Show content diff between backup and local
  list                         List locally configured entries
  ls-remote [entry|path]       List S3 entries, or files under an entry/sub-path
  help                         Show this help

Options:
  --all            Apply the command to all configured entries
  --dryrun         Show what would happen without changing anything (push)
  --delete         After restore, delete local files not in backup (pull only)
  --meta-only      Sync only metadata (ls-l.txt), skip file data (push/pull)
  --data-only      Sync only file data, leave manifest/local-meta untouched (push/pull)
  -o, --output <path>  Restore destination for pull (default: entry's configured path)
  -v, --verbose    Verbose output (details per field in status)
  --color[=WHEN]   Colorize status (verbose) and diff output
                   (WHEN: auto|always|never; default auto).
                   --color alone == --color=always. Honors NO_COLOR env var.
  --no-color       Disable color (same as --color=never)
  -h, --help       Show this help

status letters (push-oriented: what would change on the backup):
  M <path>         modified (metadata differs between local and backup)
  A <path>         only locally, not in backup   (push would add)
  D <path>         only in backup, not locally   (push would delete)

Config file: {config_path}

Examples:
  # push: back up one or more entries (or sub-paths)
  s3bak push bin .bash.d               # push selected entries
  s3bak push --all                     # push every configured entry
  s3bak push --all --dryrun            # preview without uploading
  s3bak push --meta-only bin           # upload metadata (ls-l.txt) only
  s3bak push --meta-only --all         # upload metadata for all entries
  s3bak push --data-only bin           # upload data only, leave manifest unchanged
  s3bak push bin/s3bak                 # single file inside the bin entry
  s3bak push ~/bin/s3bak               # same, via ~ expansion
  s3bak push bin/subdir                # only the sub-directory

  # pull: restore from the backup (single entry/path; use --all for every entry)
  s3bak pull bin                       # restore to the configured path
  s3bak pull bin -o /tmp/restore       # restore to an alternative path
  s3bak pull bin --delete              # also remove local files not in backup
  s3bak pull --all                     # restore every entry in parallel
  s3bak pull --meta-only bin           # restore metadata only (no file download)
  s3bak pull --data-only bin           # restore file data only (no mode/mtime applied)
  s3bak pull bin/s3bak                 # restore a single file
  s3bak pull bin/subdir -o /tmp/restore # restore a sub-tree elsewhere

  # show: print a single backed-up file to stdout
  s3bak show wsl.conf                  # single-file entry (no slash = entry name)
  s3bak show bin/s3bak                 # local path, CWD-relative
  s3bak show ~/bin/s3bak               # local path with ~ expansion
  s3bak show /home/me/bin/s3bak | less # absolute local path

  # status: compare local vs backup (metadata only, both directions)
  s3bak status bin                     # M/A/D summary for one entry
  s3bak status --all                   # status of every entry
  s3bak status -v bin                  # verbose per-field differences
  s3bak status bin/s3bak               # status of a single sub-path

  # diff: content diff between backup and local
  s3bak diff bin                       # diff the whole entry
  s3bak diff bin/s3bak                 # single-file diff, CWD-relative local path
  s3bak diff ~/bin/s3bak               # single-file diff with ~ expansion

  # list: locally configured entries (no S3 access)
  s3bak list

  # ls-remote: what is on S3
  s3bak ls-remote                      # list entries stored on S3
  s3bak ls-remote bin                  # list files recorded in bin's manifest
  s3bak ls-remote bin/subdir           # list manifest lines under a sub-path
"""
    sys.stderr.write(text)
    sys.exit(status)


# =============================================================================
# Main
# =============================================================================


def _normalize_local_path(arg: str) -> str:
    expanded = expand_home(arg) if arg.startswith("~") else arg
    return os.path.abspath(expanded)


def _resolve_one_arg(cfg: Config, arg: str) -> tuple[str, str | None]:
    # No '/': match strictly as an entry name.
    # Contains '/': treat as a local path made absolute against CWD/HOME,
    #   then find which entry's path contains it, preferring the longest prefix.
    if "/" not in arg:
        if arg in cfg.entries:
            return arg, None
        die(f"no such entry: {arg}")

    local = _normalize_local_path(arg)
    best_name: str | None = None
    best_path: str = ""
    best_file: str | None = None
    for name, entry_cfg in cfg.entries.items():
        raw_path: str = entry_cfg["path"]
        entry_path = _normalize_local_path(raw_path)
        if local == entry_path:
            candidate_file: str | None = None
        elif local.startswith(entry_path + "/"):
            candidate_file = local[len(entry_path) + 1 :]
        else:
            continue
        if best_name is None or len(entry_path) > len(best_path):
            best_name = name
            best_path = entry_path
            best_file = candidate_file

    if best_name is None:
        die(f"no such entry for path: {arg}")
    return best_name, best_file


def resolve_entry_file(cfg: Config, positional: list[str], cmd: str) -> tuple[str, str | None]:
    if len(positional) != 1:
        die(f"{cmd} takes <entry> or <path>")
    return _resolve_one_arg(cfg, positional[0])


def resolve_entry_files(
    cfg: Config, positional: list[str], cmd: str
) -> list[tuple[str, str | None]]:
    if not positional:
        die(f"{cmd} requires at least one entry or path")
    return [_resolve_one_arg(cfg, arg) for arg in positional]


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if not args:
        print_usage()

    subcmd = args[0]
    if subcmd in ("help", "-h", "--help"):
        print_usage(0)

    cfg = load_config()

    opt_all = False
    opt_dryrun = False
    opt_delete = False
    opt_meta_only = False
    opt_data_only = False
    opt_verbose = False
    opt_outpath: str | None = None
    opt_color: str = "auto"
    positional: list[str] = []

    def take_value(flag: str, idx: int) -> tuple[str, int]:
        # Support both --flag=value and --flag value
        if "=" in flag:
            return flag.split("=", 1)[1], idx
        if idx + 1 >= len(args):
            die(f"{flag} requires a value")
        return args[idx + 1], idx + 1

    i = 1
    while i < len(args):
        a = args[i]
        if a == "--all":
            opt_all = True
        elif a in ("--dryrun", "--dry-run"):
            opt_dryrun = True
        elif a == "--delete":
            opt_delete = True
        elif a == "--meta-only":
            opt_meta_only = True
        elif a == "--data-only":
            opt_data_only = True
        elif a in ("-v", "--verbose"):
            opt_verbose = True
        elif a in ("-o", "--output", "--outpath") or a.startswith(("--output=", "--outpath=")):
            opt_outpath, i = take_value(a, i)
        elif a == "--color":
            opt_color = "always"
        elif a.startswith("--color="):
            val = a.split("=", 1)[1]
            if val not in ("auto", "always", "never"):
                die(f"invalid --color value: {val} (use auto|always|never)")
            opt_color = val
        elif a == "--no-color":
            opt_color = "never"
        elif a in ("-h", "--help"):
            print_usage(0)
        elif a == "--":
            positional.extend(args[i + 1 :])
            break
        elif a.startswith("-"):
            die(f"unknown option: {a}")
        else:
            positional.append(a)
        i += 1

    opts = Opts(
        dryrun=opt_dryrun,
        delete=opt_delete,
        meta_only=opt_meta_only,
        data_only=opt_data_only,
        verbose=opt_verbose,
        outpath=opt_outpath,
        color=opt_color,
    )

    if opt_all and positional:
        die("--all cannot be combined with explicit entries")

    if opt_meta_only and opt_data_only:
        die("--meta-only and --data-only are mutually exclusive")

    if subcmd == "push":
        if opt_all:
            entries = sorted(cfg.entries.keys())
            sub_by_entry: dict[str, str | None] = {e: None for e in entries}
        else:
            resolved = resolve_entry_files(cfg, positional, "push")
            seen: set[str] = set()
            for e, _s in resolved:
                if e in seen:
                    die(
                        f"duplicate entry in push: {e} "
                        f"(parallel push of the same entry is not supported)"
                    )
                seen.add(e)
            entries = [e for e, _ in resolved]
            sub_by_entry = {e: s for e, s in resolved}

        def _push_one(cfg_: Config, entry_: str, opts_: Opts) -> int:
            return cmd_push(cfg_, entry_, opts_, sub=sub_by_entry.get(entry_))

        return run_entries(_push_one, cfg, entries, opts)

    elif subcmd == "pull":
        if opt_all:
            if opts.outpath:
                die("--all cannot be combined with -o/--output")
            return run_entries(cmd_pull, cfg, sorted(cfg.entries.keys()), opts)
        entry, sub = resolve_entry_file(cfg, positional, "pull")
        return cmd_pull(cfg, entry, opts, sub=sub)

    elif subcmd == "status":
        if opt_delete:
            die("status does not support --delete (use 'pull --delete' to remove local extras)")
        if opt_meta_only:
            die("status does not support --meta-only")
        if opt_data_only:
            die("status does not support --data-only")
        if opt_all:
            entries = sorted(cfg.entries.keys())
            status_sub_by_entry: dict[str, str | None] = {e: None for e in entries}
        else:
            resolved = resolve_entry_files(cfg, positional, "status")
            entries = [e for e, _ in resolved]
            status_sub_by_entry = {}
            for e, s in resolved:
                if e in status_sub_by_entry and status_sub_by_entry[e] != s:
                    die(f"conflicting sub paths for entry {e}")
                status_sub_by_entry[e] = s

        def _status_one(cfg_: Config, entry_: str, opts_: Opts) -> int:
            return cmd_status(cfg_, entry_, opts_, sub=status_sub_by_entry.get(entry_))

        return run_entries(_status_one, cfg, entries, opts)

    elif subcmd == "diff":
        if opt_all:
            die("diff does not support --all")
        if opt_meta_only:
            die("diff does not support --meta-only")
        if opt_data_only:
            die("diff does not support --data-only")
        entry, file = resolve_entry_file(cfg, positional, "diff")
        return cmd_diff(cfg, entry, opts, file)

    elif subcmd == "show":
        if opt_all:
            die("show does not support --all")
        if opt_meta_only:
            die("show does not support --meta-only")
        if opt_data_only:
            die("show does not support --data-only")
        entry, file = resolve_entry_file(cfg, positional, "show")
        return cmd_show(cfg, entry, opts, file)

    elif subcmd == "list":
        if opt_all:
            die("list does not support --all")
        if opt_meta_only:
            die("list does not support --meta-only")
        if opt_data_only:
            die("list does not support --data-only")
        if positional:
            die("list takes no arguments (use 'ls-remote <entry>' for manifest contents)")
        return cmd_list(cfg, opts)

    elif subcmd == "ls-remote":
        if opt_all:
            die("ls-remote does not support --all")
        if opt_meta_only:
            die("ls-remote does not support --meta-only")
        if opt_data_only:
            die("ls-remote does not support --data-only")
        if len(positional) > 1:
            die("ls-remote takes at most one entry or path")
        if not positional:
            return cmd_ls_remote(cfg, opts, None, None)
        entry, sub = _resolve_one_arg(cfg, positional[0])
        return cmd_ls_remote(cfg, opts, entry, sub)

    else:
        err(f"unknown command: {subcmd}")
        print_usage()


def _sdk_errors() -> tuple[type[BaseException], ...]:
    """The boto3-s3 / botocore error types, imported lazily so `help` / `list`
    stay SDK-free (the except clause only evaluates this on an error). Returns an
    empty tuple if the SDK is unimportable, so matching never masks the original
    error with an ImportError."""
    try:
        from boto3_s3 import Boto3S3Error
        from botocore.exceptions import BotoCoreError, ClientError
    except ImportError:
        return ()
    return (Boto3S3Error, BotoCoreError, ClientError)


def run() -> int:
    """Console entry point: install signal handling and translate exceptions
    into exit codes. This is what the ``s3bak`` command invokes."""
    signal.signal(signal.SIGINT, lambda *_: sys.exit(130))
    try:
        return main() or 0
    except subprocess.CalledProcessError as e:
        cmd_str = shlex.join(e.cmd) if isinstance(e.cmd, list) else str(e.cmd)
        err(f"command failed: {cmd_str}")
        return e.returncode or 1
    except BrokenPipeError:
        return 141
    except _sdk_errors() as e:
        err(str(e))
        return 1


if __name__ == "__main__":
    sys.exit(run())
